#https://stackoverflow.com/questions/38504257/mysql-scripts-in-docker-entrypoint-initdb-are-not-executed
#https://stackoverflow.com/questions/48105051/docker-how-to-take-a-look-at-the-tables-inside-mysql-volume

version: "3.9"  # optional since v1.27.0

services:

    rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3.9-management
        #volumes:
        #    - /home/admin/rabbit/
        ports:
            # AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'
        networks:
          messageryRoute:
            ipv4_address: 172.40.1.13

    api:
        container_name: "api"
        build: ./api
        restart: always
        volumes:
            - ./api:/home
            - ./rabbitmq:/home/rabbitmq
        working_dir: "/home"
        ports:
          - "5000:5000"
        networks:
            messageryRoute:
              ipv4_address: 172.40.1.12
        tty: true
        depends_on:
          - rabbitmq

    stock:
        container_name: "stock-agent"
        build: ./agents/stock
        restart: always
        volumes:
            - ./agents/stock:/home
            - ./rabbitmq:/home/rabbitmq
        working_dir: "/home"
        networks:
            messageryRoute:
              ipv4_address: 172.40.1.30
        tty: true
        depends_on:
          - rabbitmq

    stock-shelves:
        container_name: "stock-shelves-agent"
        build: ./agents/stock-shelves
        restart: always
        volumes:
            - ./agents/stock-shelves:/home
            - ./rabbitmq:/home/rabbitmq
        working_dir: "/home"
        networks:
            messageryRoute:
              ipv4_address: 172.40.1.31
        tty: true
        depends_on:
          - rabbitmq

    shelves:
        container_name: "shelves-agent"
        build: ./agents/shelves
        restart: always
        volumes:
            - ./agents/shelves:/home
            - ./rabbitmq:/home/rabbitmq
        working_dir: "/home"
        networks:
            messageryRoute:
              ipv4_address: 172.40.1.32
        tty: true
        depends_on:
          - rabbitmq

    mariadb:
        container_name: "mariadb"
        image: mariadb
        restart: always
        environment:
          MARIADB_ROOT_PASSWORD: 'root'
        ports:
          - "3305:3306"
        volumes:
          - ./mysqldb/dbdata:/var/lib/mysql
          - ./mysqldb/start-scripts:/docker-entrypoint-initdb.d
        networks:
          messageryRoute:
            ipv4_address: 172.40.1.15

    elasticsearch:
        build:
          context: elk/elasticsearch/
          args:
            ELK_VERSION: $ELK_VERSION
        volumes:
          - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          ES_JAVA_OPTS: "-Xmx256m -Xms256m"
          ELASTIC_PASSWORD: changeme
        networks:
          - elk
    
    logstash:
        build:
          context: elk/logstash/
          args:
            ELK_VERSION: $ELK_VERSION
        volumes:
          - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
          - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
        ports:
          - "5044:5044"
          - "9600:9600"
        environment:
          LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
          - elk
          - messageryRoute
        depends_on:
          - elasticsearch
    
    kibana:
        build:
          context: elk/kibana/
          args:
            ELK_VERSION: $ELK_VERSION
        volumes:
          - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        ports:
          - "5601:5601"
        networks:
          - elk
        depends_on:
          - elasticsearch


networks: 
  
  elk:
    driver: bridge

  messageryRoute:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.40.1.0/24"
          gateway: "172.40.1.11"

volumes:
  mysqldb:
